name: On push to main

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MOMENTO_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      MOMENTO_CACHE_NAME: laravel-cache-test

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          extensions: grpc
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: php vendor/phpunit/phpunit/phpunit --configuration phpunit.xml

      - name: Generate README
        uses: momentohq/standards-and-practices/github-actions/generate-and-commit-oss-readme@gh-actions-v1
        with:
          project_status: official
          project_stability: alpha
          project_type: other
