name: On push to main

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      MOMENTO_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      MOMENTO_CACHE_NAME: laravel-cache-test

    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          extensions: grpc
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: php vendor/phpunit/phpunit/phpunit --configuration phpunit.xml

      - uses: google-github-actions/release-please-action@v3
        name: Release Please
        id: release
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          release-type: simple
          package-name: helloworld
          bump-minor-pre-major: true
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
          extra-files: |
            version.txt

      - name: Publish
        run: |
          cat version.txt
          echo ${{ steps.release.outputs.tag_name }}
        if: ${{ steps.release.outputs.release_created }}
